### ISSUE TITLE
Date not set

### ISSUE THREAD

**Issue by nishithvpoojary** [Azure/azure-sphere-gallery#28]
Thanks for the code. 
![image](https://user-images.githubusercontent.com/45986919/114007318-dd3d1080-987e-11eb-8866-c791b5a0a978.png)

This was my output . How can I fix the date?

**Comment by mikehall-ms** [comment]
Did you obtain an API Key from https://timezonedb.com/ - the API key needs to be set in settime.c, line 17.

**Comment by tokenstar** [comment]
@nishithvpoojary  if the above fixed the issue, please close this. thanks!
